### PR TITLE
fix: WebDAV origin url with url pathname.

### LINKED ISSUE #752: pcloud与yandex的webdav无法连接
添加pcloud和yandex webdav,弹出http error 。头疼。

### LINKED ISSUE #758: WebDAV not working
Just discovers your nice and promising ff add-on - webclipper THANKS ... and it is suppose to work also with WebDAV too.   :-) 

I´m using a great- social network app called hubzilla 

https://hubzilla.org//page/hubzilla/hubzilla-project
https://framagit.org/hubzilla/core

and it works also with WebDAV very well 

https://hub.netzgemeinde.eu/help/de/member/member_guide#Personal_Cloud_Storage

but I could not connect by webclipper. 
I´m doing something wrong? 
Do you think it could work?
Thanks a lot

### LINKED ISSUE #901: WEBDAV地址不能输入特殊字符
**Bug 描述**

webdav地址不能直接输入端口号符号：，也不能输入\

导致地址不完整无法使用

我用的是synology自建webdav

### LINKED ISSUE #1025: WebDAV not working with Nextcloud WebDAV
**Describe the bug**

The clipper does not accept bind URLs for Nextcloud webDAV ( eg: https://example.com/remote.php/dav/files/user1/)

**To Reproduce**

Any Nextcloud instance

**Expected behavior**

- Browser Edge

**Additional context**

### LINKED ISSUE #1030: 希望支持本地WebDav功能！
**Bug 描述**

1. 下载https://github.com/hacdias/webdav的二进制包；
2. 配置yaml，设置端口为80，删除不必要的用户，设置共享位置与modify权限；
3. 启动webadv，设置webcliper的webdav为http://127.0.0.1，添加账号密码；
4. 使用剪藏功能：“保存内容”按钮是灰色的！

**复现步骤**

1. 下载https://github.com/hacdias/webdav的二进制包；
2. 配置yaml，设置端口为80，删除不必要的用户，设置共享位置与modify权限；
3. 启动webadv，设置webcliper的webdav为http://127.0.0.1，添加账号密码；
4. 使用剪藏功能：“保存内容”按钮是灰色的！

**预期行为**

1. 预期应该能够保存下来
2. 应该能够输入任意端口的ip地址，而不是强制使用80端口！

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: WebDav
- 浏览器 chrome
- 版本 98.0.4758.102

**其他背景**

在此处添加有关该问题的任何其他上下文。

### LINKED ISSUE #1169: 能否支持 teracloud webdav （或如何解决添加 teracloud webdav 时出现的 http error）
**您的功能要求与问题有关吗？ 请描述。**

目前 Teracloud 应用很广，不知作者有否支持 TeraCloud 的计划

**描述您想要的解决方案**

TeraCloud 有 webdav 功能，添加时出现 http error

TeraCloud webdav 网址一般为 https://abc.teracloud.jp/dav/

**描述您考虑过的替代方案**

对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**

在此处添加有关功能请求的其他任何上下文或屏幕截图。

### PR DESCRIPTION
**Pull request by IvanLi-CN**
Supports user-defined full WebDAV origin URL.

Origin such as cloudreve with URL paths will be able to be used.

Maybe fix #1169, fix #1025, fix #752, fix #901, fix #758, fix #1030.

### CODE REVIEW

**Comment by wdjoys** [comment]
@IvanLi-CN 大佬，有修复webdav问题，打包好的文件吗

**Comment by DiamondYuan** [comment]
@IvanLi-CN  能否合并一下 master 最新的代码？ master 上已经安装了 webdav, 无需新增 webdav 依赖。

PR 代码不要修改 yarn.lock

**Comment by IvanLi-CN** [comment]
@DiamondYuan 我已经变基到 master 了，但是遇到了一点问题。

 master 安装了[只支持 ESM 的 webdav v5](https://github.com/perry-mitchell/webdav-client#:~:text=Versions%203/4%20supported%20a%20UMD%2Dstyle%20module%20in%20the%20browser%2C%20but%20this%20is%20no%20longer%20supported%20in%20version%205.%20Version%205%20provides%20only%20an%20ESM%2Denabled%20bundle%20that%20can%20be%20imported%20into%20other%20ESM%2Dsupporting%20projects.) ，当前的项目是否支持 ESM？

> Versions 3/4 supported a UMD-style module in the browser, but this is no longer supported in version 5. Version 5 provides only an ESM-enabled bundle that can be imported into other ESM-supporting projects.

**Comment by weixie4** [comment]
Is this available in version 1.35 currently on Chrome store?

**Pull request merged**
